# Generated by Django 3.0.3 on 2020-06-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
