# Generated by Django 3.0.3 on 2020-06-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(default='', upload_to='student_images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Admission_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
